### ISSUE TITLE
If you can parse a glyph visually to generate a code string

### ISSUE THREAD

**Issue by lancejpollard** [LingDong-/rrpl#4]
I'm wondering if you can go from `character -> code string` automatically. I'm not sure exactly what the [parser](https://github.com/LingDong-/rrpl/blob/master/rrpl_parser.js) does, but I think it's probably parsing the _code string_ rather than visually parsing a unicode glyph and then outputing some sort of tree of strokes or something, which you would then use somehow to automatically figure out how to generate the appropriate/approximate codes out of.

If you're not automatically doing it, I'd be interested to know how you've done 5,000+ glyphs already! It would seem only then that you must have done them by hand! That would be a lot of work but it would make sense :) Interested to know how you did/do that part of the process.

If you do it manually, by looking at the glyph and mentally (or with pen/paper sort of thing) overlaying a grid over an zoomed in glyph, then I'm wondering what your technique is to efficiently figuring out (manually though) the code string that accurately represents it.

I can understand how your AI generation thing might work, which generated potential new characters. This would just iterate through the possible code strings you could make and go from there. But this other problem of figuring out how to find the code string for a given glyph seems pretty hard.

**Comment by LingDong-** [comment]
Hi there, thanks for your interest in the project!

I hand coded the 5,000+ glyphs manually. At first it was slow but it becomes much faster later 
since new characters are often just combination of previous ones. I worked on it sporadically over a couple of months.

My technique is basically just looking at the glyph and typing up the code. I also made [a preview tool](https://chinese-radical-vis.glitch.me//lab/index.html) so I can see what I'm building in realtime. The task takes some brainpower at first, but gradually becomes natural.

And you're right about what the parser does. :)
